mybatis:
  mapper-locations: classpath:mappers/*.xml
  
server:
  port: 8088
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: 12345
    url: jdbc:mysql://project-db-stu.ddns.net:3307/Anjisu
    #url: jdbc:log4jdbc:mysql://project-db-stu.ddns.net:3307/Anjisu
    username: Anjisu
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache : false
    view-names: th/*
    
logging:
  level:
    jdbc.sqlonly: DEBUG ## 이부분 추가.